//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Proyecto_OCS_IngSoftwareEntities : DbContext
    {
        public Proyecto_OCS_IngSoftwareEntities()
            : base("name=Proyecto_OCS_IngSoftwareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_MENU> T_MENU { get; set; }
        public virtual DbSet<T_MESAS> T_MESAS { get; set; }
        public virtual DbSet<T_ORDENES> T_ORDENES { get; set; }
        public virtual DbSet<T_ORDENES_PLATOS> T_ORDENES_PLATOS { get; set; }
        public virtual DbSet<T_USUARIOS> T_USUARIOS { get; set; }
        public virtual DbSet<T_TEMP_ORDENES> T_TEMP_ORDENES { get; set; }
    
        public virtual ObjectResult<sp_ConsultaPorIdentificacion_Result> sp_ConsultaPorIdentificacion(string identificacion_persona)
        {
            var identificacion_personaParameter = identificacion_persona != null ?
                new ObjectParameter("identificacion_persona", identificacion_persona) :
                new ObjectParameter("identificacion_persona", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaPorIdentificacion_Result>("sp_ConsultaPorIdentificacion", identificacion_personaParameter);
        }
    
        public virtual int sp_GenerarNuevoPassword(string identificacion, Nullable<int> length)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("identificacion", identificacion) :
                new ObjectParameter("identificacion", typeof(string));
    
            var lengthParameter = length.HasValue ?
                new ObjectParameter("length", length) :
                new ObjectParameter("length", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GenerarNuevoPassword", identificacionParameter, lengthParameter);
        }
    
        public virtual int sp_InsertarPlato(string nombre, string descripcion, Nullable<decimal> precio, string usuario_registra, Nullable<System.DateTime> fechahoraregistro)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var usuario_registraParameter = usuario_registra != null ?
                new ObjectParameter("usuario_registra", usuario_registra) :
                new ObjectParameter("usuario_registra", typeof(string));
    
            var fechahoraregistroParameter = fechahoraregistro.HasValue ?
                new ObjectParameter("fechahoraregistro", fechahoraregistro) :
                new ObjectParameter("fechahoraregistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarPlato", nombreParameter, descripcionParameter, precioParameter, usuario_registraParameter, fechahoraregistroParameter);
        }
    
        public virtual int sp_InsertarUsuario(string nombre, string identificacion, string celular, string email, string perfil, string usuario_registra, Nullable<System.DateTime> fechahoraregistro, Nullable<int> length)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("identificacion", identificacion) :
                new ObjectParameter("identificacion", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("celular", celular) :
                new ObjectParameter("celular", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var perfilParameter = perfil != null ?
                new ObjectParameter("perfil", perfil) :
                new ObjectParameter("perfil", typeof(string));
    
            var usuario_registraParameter = usuario_registra != null ?
                new ObjectParameter("usuario_registra", usuario_registra) :
                new ObjectParameter("usuario_registra", typeof(string));
    
            var fechahoraregistroParameter = fechahoraregistro.HasValue ?
                new ObjectParameter("fechahoraregistro", fechahoraregistro) :
                new ObjectParameter("fechahoraregistro", typeof(System.DateTime));
    
            var lengthParameter = length.HasValue ?
                new ObjectParameter("length", length) :
                new ObjectParameter("length", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarUsuario", nombreParameter, identificacionParameter, celularParameter, emailParameter, perfilParameter, usuario_registraParameter, fechahoraregistroParameter, lengthParameter);
        }
    
        public virtual int sp_ModificarEstadoUsuario(string identificacion, string estado_actual)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("identificacion", identificacion) :
                new ObjectParameter("identificacion", typeof(string));
    
            var estado_actualParameter = estado_actual != null ?
                new ObjectParameter("estado_actual", estado_actual) :
                new ObjectParameter("estado_actual", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarEstadoUsuario", identificacionParameter, estado_actualParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarPlatoPorID_Result> sp_ConsultarPlatoPorID(Nullable<int> idPlato)
        {
            var idPlatoParameter = idPlato.HasValue ?
                new ObjectParameter("idPlato", idPlato) :
                new ObjectParameter("idPlato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarPlatoPorID_Result>("sp_ConsultarPlatoPorID", idPlatoParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarPlatos_Result> sp_ConsultarPlatos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarPlatos_Result>("sp_ConsultarPlatos");
        }
    
        public virtual int sp_ModificarPlato(Nullable<int> id_plato, string descripcion, Nullable<decimal> precio)
        {
            var id_platoParameter = id_plato.HasValue ?
                new ObjectParameter("id_plato", id_plato) :
                new ObjectParameter("id_plato", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarPlato", id_platoParameter, descripcionParameter, precioParameter);
        }
    
        public virtual int sp_ModificarEstadoPlato(Nullable<int> idPlato, string estado_actual)
        {
            var idPlatoParameter = idPlato.HasValue ?
                new ObjectParameter("idPlato", idPlato) :
                new ObjectParameter("idPlato", typeof(int));
    
            var estado_actualParameter = estado_actual != null ?
                new ObjectParameter("estado_actual", estado_actual) :
                new ObjectParameter("estado_actual", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarEstadoPlato", idPlatoParameter, estado_actualParameter);
        }
    
        public virtual int sp_CrearMesa(Nullable<int> num_mesa, Nullable<int> ln_cantidad_personas, string lv_id_user)
        {
            var num_mesaParameter = num_mesa.HasValue ?
                new ObjectParameter("num_mesa", num_mesa) :
                new ObjectParameter("num_mesa", typeof(int));
    
            var ln_cantidad_personasParameter = ln_cantidad_personas.HasValue ?
                new ObjectParameter("Ln_cantidad_personas", ln_cantidad_personas) :
                new ObjectParameter("Ln_cantidad_personas", typeof(int));
    
            var lv_id_userParameter = lv_id_user != null ?
                new ObjectParameter("Lv_id_user", lv_id_user) :
                new ObjectParameter("Lv_id_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearMesa", num_mesaParameter, ln_cantidad_personasParameter, lv_id_userParameter);
        }
    
        public virtual ObjectResult<sp_ConsultaMesas_Result> sp_ConsultaMesas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaMesas_Result>("sp_ConsultaMesas");
        }
    
        public virtual int sp_ModificarEstadoMesa(Nullable<int> idMesa, string estado_actual)
        {
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("idMesa", idMesa) :
                new ObjectParameter("idMesa", typeof(int));
    
            var estado_actualParameter = estado_actual != null ?
                new ObjectParameter("estado_actual", estado_actual) :
                new ObjectParameter("estado_actual", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarEstadoMesa", idMesaParameter, estado_actualParameter);
        }
    
        public virtual ObjectResult<sp_consultaMesaPorID_Result> sp_consultaMesaPorID(Nullable<int> idMesa)
        {
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("idMesa", idMesa) :
                new ObjectParameter("idMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultaMesaPorID_Result>("sp_consultaMesaPorID", idMesaParameter);
        }
    
        public virtual ObjectResult<sp_ListadoPlatillosPendientes_Result> sp_ListadoPlatillosPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListadoPlatillosPendientes_Result>("sp_ListadoPlatillosPendientes");
        }
    
        public virtual int sp_ActualizaOrdenPlato(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaOrdenPlato", idParameter);
        }
    
        public virtual ObjectResult<sp_ListadodePlatillosPendientes_Result> sp_ListadodePlatillosPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListadodePlatillosPendientes_Result>("sp_ListadodePlatillosPendientes");
        }
    
        public virtual ObjectResult<sp_ConsultaMesasHabilitadas_Result> sp_ConsultaMesasHabilitadas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaMesasHabilitadas_Result>("sp_ConsultaMesasHabilitadas");
        }
    
        public virtual ObjectResult<sp_ConsultarPlatosHabilitados_Result> sp_ConsultarPlatosHabilitados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarPlatosHabilitados_Result>("sp_ConsultarPlatosHabilitados");
        }
    
        public virtual int sp_InsertaRegistroTemporal(Nullable<int> num_mesa, Nullable<int> id_plato, string observaciones, Nullable<int> cant, string id_mesero, string cliente, string estado)
        {
            var num_mesaParameter = num_mesa.HasValue ?
                new ObjectParameter("num_mesa", num_mesa) :
                new ObjectParameter("num_mesa", typeof(int));
    
            var id_platoParameter = id_plato.HasValue ?
                new ObjectParameter("id_plato", id_plato) :
                new ObjectParameter("id_plato", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var cantParameter = cant.HasValue ?
                new ObjectParameter("cant", cant) :
                new ObjectParameter("cant", typeof(int));
    
            var id_meseroParameter = id_mesero != null ?
                new ObjectParameter("id_mesero", id_mesero) :
                new ObjectParameter("id_mesero", typeof(string));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaRegistroTemporal", num_mesaParameter, id_platoParameter, observacionesParameter, cantParameter, id_meseroParameter, clienteParameter, estadoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ConsultaIDMesa(Nullable<int> numMesa)
        {
            var numMesaParameter = numMesa.HasValue ?
                new ObjectParameter("numMesa", numMesa) :
                new ObjectParameter("numMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ConsultaIDMesa", numMesaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ConsultaIDPlato(string nombrePlato)
        {
            var nombrePlatoParameter = nombrePlato != null ?
                new ObjectParameter("nombrePlato", nombrePlato) :
                new ObjectParameter("nombrePlato", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ConsultaIDPlato", nombrePlatoParameter);
        }
    
        public virtual int sp_EliminarRegTemp(Nullable<int> numMesa)
        {
            var numMesaParameter = numMesa.HasValue ?
                new ObjectParameter("numMesa", numMesa) :
                new ObjectParameter("numMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarRegTemp", numMesaParameter);
        }
    
        public virtual ObjectResult<sp_PlatosTemporalesPorMesa_Result> sp_PlatosTemporalesPorMesa(Nullable<int> numMesa)
        {
            var numMesaParameter = numMesa.HasValue ?
                new ObjectParameter("numMesa", numMesa) :
                new ObjectParameter("numMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PlatosTemporalesPorMesa_Result>("sp_PlatosTemporalesPorMesa", numMesaParameter);
        }
    
        public virtual ObjectResult<sp_ConsultaPlatosTempPorMesa_Result> sp_ConsultaPlatosTempPorMesa(Nullable<int> numMesa)
        {
            var numMesaParameter = numMesa.HasValue ?
                new ObjectParameter("numMesa", numMesa) :
                new ObjectParameter("numMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaPlatosTempPorMesa_Result>("sp_ConsultaPlatosTempPorMesa", numMesaParameter);
        }
    
        public virtual int sp_InsertarOrden(Nullable<int> numMesa, string mesero)
        {
            var numMesaParameter = numMesa.HasValue ?
                new ObjectParameter("numMesa", numMesa) :
                new ObjectParameter("numMesa", typeof(int));
    
            var meseroParameter = mesero != null ?
                new ObjectParameter("mesero", mesero) :
                new ObjectParameter("mesero", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarOrden", numMesaParameter, meseroParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ConsultaIdOrden(Nullable<int> numMesa)
        {
            var numMesaParameter = numMesa.HasValue ?
                new ObjectParameter("numMesa", numMesa) :
                new ObjectParameter("numMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ConsultaIdOrden", numMesaParameter);
        }
    
        public virtual int sp_InsertaOrdenPlato(Nullable<int> idOrden, Nullable<int> idPlato, string observaciones, Nullable<int> cant)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            var idPlatoParameter = idPlato.HasValue ?
                new ObjectParameter("idPlato", idPlato) :
                new ObjectParameter("idPlato", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var cantParameter = cant.HasValue ?
                new ObjectParameter("cant", cant) :
                new ObjectParameter("cant", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaOrdenPlato", idOrdenParameter, idPlatoParameter, observacionesParameter, cantParameter);
        }
    
        public virtual ObjectResult<sp_ConsultaPlatosTemporalesMesa_Result> sp_ConsultaPlatosTemporalesMesa(Nullable<int> numMesa)
        {
            var numMesaParameter = numMesa.HasValue ?
                new ObjectParameter("numMesa", numMesa) :
                new ObjectParameter("numMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaPlatosTemporalesMesa_Result>("sp_ConsultaPlatosTemporalesMesa", numMesaParameter);
        }
    
        public virtual ObjectResult<sp_ListadoComanda_Result> sp_ListadoComanda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListadoComanda_Result>("sp_ListadoComanda");
        }
    
        public virtual ObjectResult<sp_ConsultaMesasConOrdenes_Result> sp_ConsultaMesasConOrdenes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaMesasConOrdenes_Result>("sp_ConsultaMesasConOrdenes");
        }
    
        public virtual ObjectResult<sp_ConsultaPlatillosOrden_Result> sp_ConsultaPlatillosOrden(Nullable<int> num_mesa)
        {
            var num_mesaParameter = num_mesa.HasValue ?
                new ObjectParameter("num_mesa", num_mesa) :
                new ObjectParameter("num_mesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaPlatillosOrden_Result>("sp_ConsultaPlatillosOrden", num_mesaParameter);
        }
    
        public virtual ObjectResult<sp_ConsultaPlatillosDeOrden_Result> sp_ConsultaPlatillosDeOrden(Nullable<int> num_mesa)
        {
            var num_mesaParameter = num_mesa.HasValue ?
                new ObjectParameter("num_mesa", num_mesa) :
                new ObjectParameter("num_mesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaPlatillosDeOrden_Result>("sp_ConsultaPlatillosDeOrden", num_mesaParameter);
        }
    
        public virtual int sp_EliminarRegOrdenPlato(Nullable<int> idReg)
        {
            var idRegParameter = idReg.HasValue ?
                new ObjectParameter("idReg", idReg) :
                new ObjectParameter("idReg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarRegOrdenPlato", idRegParameter);
        }
    
        public virtual ObjectResult<sp_ValidaEstadoPlatosOrden_Result> sp_ValidaEstadoPlatosOrden(Nullable<int> numMesa)
        {
            var numMesaParameter = numMesa.HasValue ?
                new ObjectParameter("numMesa", numMesa) :
                new ObjectParameter("numMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ValidaEstadoPlatosOrden_Result>("sp_ValidaEstadoPlatosOrden", numMesaParameter);
        }
    
        public virtual int sp_AnularRegOrdenPlato(Nullable<int> idOrden)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AnularRegOrdenPlato", idOrdenParameter);
        }
    
        public virtual ObjectResult<sp_TotalesLineas_Result> sp_TotalesLineas(Nullable<int> id_orden)
        {
            var id_ordenParameter = id_orden.HasValue ?
                new ObjectParameter("id_orden", id_orden) :
                new ObjectParameter("id_orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalesLineas_Result>("sp_TotalesLineas", id_ordenParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_TotalFactura(Nullable<int> id_orden)
        {
            var id_ordenParameter = id_orden.HasValue ?
                new ObjectParameter("id_orden", id_orden) :
                new ObjectParameter("id_orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_TotalFactura", id_ordenParameter);
        }
    
        public virtual int sp_FinalizarOrden(Nullable<int> id_orden)
        {
            var id_ordenParameter = id_orden.HasValue ?
                new ObjectParameter("id_orden", id_orden) :
                new ObjectParameter("id_orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FinalizarOrden", id_ordenParameter);
        }
    
        public virtual int sp_AnularOrden(Nullable<int> idOrden)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AnularOrden", idOrdenParameter);
        }
    }
}
