//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEMP_ORDENES
    {
        public int NUM_MESA { get; set; }
        public int ID_PLATO { get; set; }
        public string ID_MESERO { get; set; }
        public string CLIENTE_NOMBRE { get; set; }
        public string ESTADO { get; set; }
        public int CANTIDAD { get; set; }
        public string observaciones { get; set; }
    }
}
